server:
  port: 9100
eureka:
  instance:
    hostname: 127.0.0.1
    server-port: 8000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server-port}/eureka