server:
  port: 8000

spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dyqin/spring-cloud-study
          searchPaths: config-repo/license-service
          username: deyuanqin@163.com
          password: ZHIhuzheye111
          default-label: master

